[platformio]
src_dir = .

[env:genericGD32F130C8]
platform = https://github.com/CommunityGD32Cores/platform-gd32.git
board = genericGD32F130C8
framework = spl

upload_protocol = stlink
debug_tool = stlink

monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
monitor_port = /dev/ttyUSB0

build_flags = -D__SYSTEM_CLOCK_48M_PLL_HSI